
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpepojevzyhepyhshdgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wZXBvamV2enloZXB5aHNoZGdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3ODA3MjQsImV4cCI6MjA2MDM1NjcyNH0.BWr55hph3tfDWuv0lbxo-cDSJdUCoKqvBQmHBIkx8-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
